name: job fails also run workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: failure job
        run: exit 1

  job2:
    needs: job1
    if: $ {{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: continue job2
        run: echo "this runs even if job1 fails"

  job3:
    needs: job2
    if: $ {{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: continue job3
        run: echo "this runs even if job2 fails"
