name: Simple 3 Job Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build step
        run: exit

  test:
    runs-on: ubuntu-latest
    needs: build   # runs after build job
    steps:
      - name: Run tests
        run: echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: test    # runs after test job
    steps:
      - name: Deploy application
        run: echo "Deploying application..."
